# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/id-fastcore',
                'doc_host': 'https://Iamalos.github.io',
                'git_url': 'https://github.com/Iamalos/id-fastcore',
                'lib_path': 'id_fastcore'},
  'syms': {'id_fastcore.core': {'id_fastcore.core.foo': ('core.html#foo', 'id_fastcore/core.py')}}}
